package dto;

public enum TipoOperazione {
    LOGIN,
    REGISTRA_UTENTE,
    AGGIUNGI_RISTORANTE,
    CERCA_RISTORANTI,
    AGGIUNGI_RECENSIONE,
    AGGIUNGI_PREFERITO,
    RIMUOVI_PREFERITO,
    VISUALIZZA_PREFERITI,
    RISPONDI_RECENSIONE
}
